---
- name: Create panda group
  group: 
    name: panda 
    state: present
 
- name: Create panda user belonging to sudo and panda groups
  user:
    name: panda
    shell: /bin/bash
    groups: 
      - panda
      - sudo
 
- name: Set authorized key for user panda copying it from vagrant user
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"